# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
<<<<<<< HEAD
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
=======
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

>>>>>>> 7c309a739eaed38706e42cda2caa53bced11c17a
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ðŸ“¦
        #Using npm ci is generally faster than running npm install
        run: |
          npm ci
      - name: Build the app ðŸ—
        run: |
          npm run build
      - name: Run component tests ðŸ”¸
        run: |
          npm run test
      - name: Start the app ðŸ“¤
        run: |
          npm start &
          npx wait-on --timeout 60000
=======
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies ðŸ“¦
      #Using npm ci is generally faster than running npm install
      run: |
        npm ci
    - name: Build the app ðŸ—
      run: |
        npm run build
    - name: Run component tests ðŸ”¸
      run: |
        npm run test
    - name: Start the app ðŸ“¤
      run: |
        npm start &
        npx wait-on --timeout 60000
>>>>>>> 7c309a739eaed38706e42cda2caa53bced11c17a
